import type { InsertableComponent } from "./index"

export const GITLAB_COMPONENTS: InsertableComponent[] = [
  {
    id: "inline-diff",
    label: "Inline Diff",
    description: "Insert an inline diff",
    icon: "diff",
    template: "{+ added feature +}\n{- removed feature -}\n\n",
  },
  {
    id: "description-list",
    label: "Description List",
    description: "Insert a description list",
    icon: "list",
    template: "Term 1\n: Definition 1\n\nTerm 2\n: Definition 2\n\n",
  },
  {
    id: "task-list-gl",
    label: "Task List",
    description: "Insert a task list",
    icon: "list-task",
    template: "- [ ] Task 1\n- [~] Task 2\n- [x] Task 3\n",
  },
  {
    id: "table-gl",
    label: "Table",
    description: "Insert a table",
    icon: "table",
    template: "| Column 1 | Column 2 |\n|----------|----------|\n| Cell 1   | Cell 2   |\n",
  },
  {
    id: "collapsible-section-gl",
    label: "Collapsible Section",
    description: "Insert a collapsible section",
    icon: "collapse",
    template:
      "<details>\n  <summary>Click to expand</summary>\n\n  Collapsible content goes here.\n\n</details>\n\n",
  },
  {
    id: "note-gl",
    label: "Note",
    description: "Insert a note block",
    icon: "note",
    template: "> [!NOTE]\n> This is a note.\n\n",
  },
  {
    id: "tip-gl",
    label: "Tip",
    description: "Insert a tip block",
    icon: "lightbulb",
    template: "> [!TIP]\n> This is a tip.\n\n",
  },
  {
    id: "important-gl",
    label: "Important",
    description: "Insert an important block",
    icon: "important",
    template: "> [!IMPORTANT]\n> This is important.\n\n",
  },
  {
    id: "warning-gl",
    label: "Warning",
    description: "Insert a warning block",
    icon: "warning",
    template: "> [!WARNING]\n> This is a warning.\n\n",
  },
  {
    id: "caution-gl",
    label: "Caution",
    description: "Insert a caution block",
    icon: "caution",
    template: "> [!CAUTION]\n> This is a caution.\n\n",
  },
  {
    id: "note-fenced-gl",
    label: "Note (with title)",
    description: "Insert a fenced note block with optional title",
    icon: "note",
    template: ">>> [!NOTE] Things to consider\nYour note content here.\n\n>>>\n\n",
  },
  {
    id: "tip-fenced-gl",
    label: "Tip (with title)",
    description: "Insert a fenced tip block with optional title",
    icon: "lightbulb",
    template: ">>> [!TIP] Pro tip\nYour tip content here.\n\n>>>\n\n",
  },
  {
    id: "important-fenced-gl",
    label: "Important (with title)",
    description: "Insert a fenced important block with optional title",
    icon: "important",
    template: ">>> [!IMPORTANT] Key information\nYour important content here.\n\n>>>\n\n",
  },
  {
    id: "warning-fenced-gl",
    label: "Warning (with title)",
    description: "Insert a fenced warning block with optional title",
    icon: "warning",
    template: ">>> [!WARNING] Take care\nYour warning content here.\n\n>>>\n\n",
  },
  {
    id: "caution-fenced-gl",
    label: "Caution (with title)",
    description: "Insert a fenced caution block with optional title",
    icon: "caution",
    template: ">>> [!CAUTION] Danger zone\nYour caution content here.\n\n>>>\n\n",
  },
  {
    id: "diagram-gl",
    label: "Diagram",
    description: "Insert a Mermaid diagram",
    icon: "diagram",
    template: "```mermaid\ngraph TD;\n  A-->B;\n  A-->C;\n  B-->D;\n  C-->D;\n```\n",
  },
  {
    id: "inline-math-gl",
    label: "Inline Math",
    description: "Insert inline math formula",
    icon: "math",
    template: "$E=mc^2$\n",
  },
  {
    id: "math-block-gl",
    label: "Math Block",
    description: "Insert a math block",
    icon: "math-block",
    template: "$$\nE=mc^2\n$$\n\n",
  },
  {
    id: "emoji-gl",
    label: "Emoji",
    description: "Insert an emoji",
    icon: "smile",
    template: ":smile:",
  },
]
