import type { InsertableComponent } from "./index"

export const STANDARD_COMPONENTS: InsertableComponent[] = [
  {
    id: "paragraph",
    label: "Paragraph",
    description: "Regular paragraph text",
    icon: "text",
    template: "",
    show: false,
  },
  {
    id: "heading-1",
    label: "Heading 1",
    description: "Large section heading",
    icon: "heading-1",
    template: "# Heading 1\n",
  },
  {
    id: "heading-2",
    label: "Heading 2",
    description: "Medium section heading",
    icon: "heading-2",
    template: "## Heading 2\n",
  },
  {
    id: "heading-3",
    label: "Heading 3",
    description: "Small section heading",
    icon: "heading-3",
    template: "### Heading 3\n",
  },
  {
    id: "heading-4",
    label: "Heading 4",
    description: "Subsection heading",
    icon: "heading-4",
    template: "#### Heading 4\n",
  },
  {
    id: "heading-5",
    label: "Heading 5",
    description: "Minor heading",
    icon: "heading-5",
    template: "##### Heading 5\n",
  },
  {
    id: "heading-6",
    label: "Heading 6",
    description: "Smallest heading",
    icon: "heading-6",
    template: "###### Heading 6\n",
  },
  {
    id: "heading-setext",
    label: "Setext Heading",
    description: "Setext style heading",
    icon: "heading",
    template: "Heading\n==========\n",
    show: false,
  },
  {
    id: "bold",
    label: "Bold",
    icon: "bold",
    template: "**bold text**",
    description: "Bold text",
  },
  {
    id: "italic",
    label: "Italic",
    icon: "italic",
    template: "*italic text*",
    description: "Italic text",
  },
  {
    id: "strikethrough",
    label: "Strikethrough",
    icon: "strikethrough",
    template: "~~strikethrough~~",
    description: "Strikethrough text",
  },
  {
    id: "inline-code",
    label: "Inline Code",
    icon: "code",
    template: "`code`",
    description: "Inline code snippet",
  },
  {
    id: "link",
    label: "Link",
    icon: "link",
    template: "[link text](https://example.com)",
    description: "Hyperlink",
  },
  {
    id: "image",
    label: "Image",
    icon: "image",
    template: "![alt text](https://picsum.photos/600/400)\n",
    description: "Embedded image",
  },
  {
    id: "unordered-list",
    label: "Bullet List",
    icon: "list",
    template: "- Item 1\n- Item 2\n- Item 3\n",
    description: "Unordered list",
  },
  {
    id: "ordered-list",
    label: "Numbered List",
    icon: "list-ordered",
    template: "1. First item\n2. Second item\n3. Third item\n",
    description: "Ordered list",
  },
  {
    id: "blockquote",
    label: "Blockquote",
    icon: "quote",
    template: "> Blockquote text\n",
    description: "Quoted text",
  },
  {
    id: "horizontal-rule",
    label: "Divider",
    icon: "minus",
    template: "\n---\n",
    description: "Horizontal rule",
  },
  {
    id: "code-block",
    label: "Code Block",
    icon: "file-code",
    template: '```javascript\n// Your code here\nconsole.log("Hello!");\n```\n',
    description: "Fenced code block",
  },
]
