import type { InsertableComponent } from "./index"

export const STANDARD_COMPONENTS: InsertableComponent[] = [
  {
    id: "heading-1",
    label: "Heading 1",
    description: "Large section heading",
    icon: "heading-1",
    template: "# Heading 1\n",
  },
  {
    id: "heading-2",
    label: "Heading 2",
    description: "Medium section heading",
    icon: "heading-2",
    template: "## Heading 2\n",
  },
  {
    id: "heading-3",
    label: "Heading 3",
    description: "Small section heading",
    icon: "heading-3",
    template: "### Heading 3\n",
  },
  {
    id: "heading-4",
    label: "Heading 4",
    description: "Subsection heading",
    icon: "heading-4",
    template: "#### Heading 4\n",
  },
  {
    id: "heading-5",
    label: "Heading 5",
    description: "Minor heading",
    icon: "heading-5",
    template: "##### Heading 5\n",
  },
  {
    id: "heading-6",
    label: "Heading 6",
    description: "Smallest heading",
    icon: "heading-6",
    template: "###### Heading 6\n",
  },
  {
    id: "heading-setext",
    label: "Setext Heading",
    description: "Setext style heading",
    icon: "heading",
    template: "Heading\n==========\n",
    show: false,
  },
  {
    id: "paragraph",
    label: "Paragraph",
    description: "Regular paragraph text",
    icon: "text",
    template: "",
    show: false,
  },
  {
    id: "bold",
    label: "Bold",
    icon: "bold",
    template: "**bold text**",
    description: "Bold text",
  },
  {
    id: "italic",
    label: "Italic",
    icon: "italic",
    template: "*italic text*",
    description: "Italic text",
  },
  {
    id: "strikethrough",
    label: "Strikethrough",
    icon: "strikethrough",
    template: "~~strikethrough~~",
    description: "Strikethrough text",
  },
  {
    id: "inline-code",
    label: "Inline Code",
    icon: "code",
    template: "`code`",
    description: "Inline code snippet",
  },
  {
    id: "link",
    label: "Link",
    icon: "link",
    template: "[link text](https://example.com)",
    description: "Hyperlink",
  },
  {
    id: "image",
    label: "Image",
    icon: "image",
    template: "![alt text](https://picsum.photos/600/400)\n",
    description: "Embedded image",
  },
  {
    id: "unordered-list",
    label: "Bullet List",
    icon: "list",
    template: "- Item 1\n- Item 2\n- Item 3\n",
    description: "Unordered list",
  },
  {
    id: "ordered-list",
    label: "Numbered List",
    icon: "list-ordered",
    template: "1. First item\n2. Second item\n3. Third item\n",
    description: "Ordered list",
  },
  {
    id: "blockquote",
    label: "Blockquote",
    description: "Quoted insight",
    icon: "quote",
    template: "> Blockquote\n",
  },
  {
    id: "indented-code-block",
    label: "Indented Code Block",
    description: "Indented snippet",
    icon: "code",
    template: "    code block\n",
    show: false,
  },
  {
    id: "fenced-code-block",
    label: "Code Block",
    description: "Fenced snippet",
    icon: "code",
    template: '```javascript\n// Your code here\nconsole.log("Hello World");\n```\n',
  },
  {
    id: "thematic-break",
    label: "Divider",
    description: "Section divider",
    icon: "minus",
    template: "---\n",
  },
  {
    id: "html-block",
    label: "HTML Block",
    description: "HTML section",
    icon: "braces",
    template: "<div>HTML</div>\n",
    show: false,
  },
  {
    id: "autolink",
    label: "Autolink",
    description: "Auto link",
    icon: "link",
    template: "<https://example.com>",
  },
  {
    id: "raw-html",
    label: "Raw HTML",
    description: "Inline HTML",
    icon: "terminal",
    template: "<span>HTML</span>",
  },
  {
    id: "hard-line-break",
    label: "Hard Line Break",
    description: "Forced break",
    icon: "minus",
    template: "Line 1  \nLine 2",
    show: false,
  },
  {
    id: "soft-line-break",
    label: "Soft Line Break",
    description: "Soft break",
    icon: "minus",
    template: "Line 1\nLine 2",
    show: false,
  },
  {
    id: "backslash-escape",
    label: "Backslash Escape",
    description: "Escape character",
    icon: "slash",
    template: "\\*text*",
  },
  {
    id: "character-reference",
    label: "Character Reference",
    description: "Special character",
    icon: "ampersand",
    template: "&amp; &#123;",
  },
  {
    id: "link-reference-definition",
    label: "Link Reference Definition",
    description: "Reusable link",
    icon: "link",
    template: '[label]: url "title"',
    show: false,
  },
]
